function  [Time,wQic,wQi1,wQi2,wQi3,wQi4,AccC,Acc2,Acc4] = ImportATData(filename)
% Propperly imports the data from a '.txt' file generated by the teensy

% INPUTS:
% filename - filename.txt file from which import the data

% OUTPUTS:
% Time - Time vector(s) from the TimeStamp information
% wQic - Orietnation of the chest IMU (ic) in the world reference frame (w)
% wQi1 - Orietnation of the chest IMU (i1) in the world reference frame (w)
% wQi2 - Orietnation of the chest IMU (i2) in the world reference frame (w)
% wQi3 - Orietnation of the chest IMU (i3) in the world reference frame (w)
% wQi4 - Orietnation of the chest IMU (i4) in the world reference frame (w)
% AccC - Acceleration vector from the chest IMU
% Acc2 - Acceleration vector from the right forearm IMU
% Acc4 - Acceleration vector from the left forearm IMU+

% CODE:
    Data = fileread(filename);
    Data = split(Data,';');
    for i = 1:length(Data(:,1))
        if (size(strfind(Data{i},'_'),2)~=8 || size(strfind(Data{i},','),2)~=21)
            Data{i} = Data{i-1};
        end
    end
    Data = split(Data,'_');
    TimeStamp = str2double(Data(:,1));
    Time = (TimeStamp-TimeStamp(1))/1000;
    wQic = str2double(split(Data(:,2),','));
    wQi1 = str2double(split(Data(:,3),','));
    wQi2 = str2double(split(Data(:,4),','));
    wQi3 = str2double(split(Data(:,5),','));
    wQi4 = str2double(split(Data(:,6),','));
    AccC = str2double(split(Data(:,7),','));
    Acc2 = str2double(split(Data(:,8),','));
    Acc4 = str2double(split(Data(:,9),','));
end

