install.packages("matrixStats")
library(matrixStats)
library(datasets)
data(iris)
x<-as.matrix(iris[,-5])
rm(iris)
pca<-prcomp(x,center=T,scale=T)
eigenvectors<-as.matrix(pca$rotation)
eigenvalues<-pca$sdev^2
sd<-colSds(x)
sd<-matrix(sd,nrow=nrow(x),ncol=ncol(x),byrow=TRUE)
mu<-unname(pca$center)
mu<-matrix(mu,nrow=nrow(x),ncol=ncol(x),byrow=TRUE)
indiv_components<-as.matrix(pca$x)

res<-indiv_components%*%t(eigenvectors)
res<-res+mu
res1<-scale(res)
x1<-scale(x)
